"use client";
import { FormEvent, useEffect, useState } from "react";

type User = { id: string; email?: string; role: "teacher" | "student" | null; displayName?: string };
type Work = { id: string; title: string; author?: string; genre?: string; theme?: string; summary?: string; source_text?: string; commentary: string; generated_result: any; published_at?: string };
const empty = { title: "", author: "", genre: "", sourceText: "", theme: "", expressionFeatures: "", summary: "", commentary: "" };

export default function Home() {
  const [user, setUser] = useState<User | null>(); const [token, setToken] = useState(""); const [screen, setScreen] = useState<"library" | "teacher" | "detail" | "quiz">("library");
  const [works, setWorks] = useState<Work[]>([]); const [selected, setSelected] = useState<Work>(); const [form, setForm] = useState(empty); const [quizQuestions, setQuizQuestions] = useState<any[]>([]);
  const [query, setQuery] = useState(""); const [authOpen, setAuthOpen] = useState(false); const [authMode, setAuthMode] = useState<"login" | "signup">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [answers, setAnswers] = useState<Record<string, number>>({}); const [attemptId, setAttemptId] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const publicUrl = process.env.NEXT_PUBLIC_SUPABASE_URL; const publicKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  const headers = () => ({ "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) });
  useEffect(() => { const saved = sessionStorage.getItem("literary-session"); if (saved) { const value = JSON.parse(saved); setToken(value.access_token); loadSession(value.access_token); } searchWorks(""); }, []);
  async function loadSession(value = token) { const response = await fetch("/api/session", { headers: value ? { Authorization: `Bearer ${value}` } : {} }); const data = await response.json(); setUser(data.user); }
  async function searchWorks(value = query) { try { const res = await fetch(`/api/works?q=${encodeURIComponent(value)}`); const data = await res.json(); if (res.ok) setWorks(data); } catch { setMessage("작품 목록을 불러오지 못했습니다."); } }
  async function authenticate(event: FormEvent) { event.preventDefault(); if (!publicUrl || !publicKey) return setMessage("Supabase 공개 환경 변수를 설정해 주세요."); setLoading(true); try { if (authMode === "signup") { const sign = await fetch(`${publicUrl}/auth/v1/signup`, { method: "POST", headers: { apikey: publicKey, "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await sign.json(); if (!sign.ok) throw new Error(data.msg || data.error_description); if (!data.access_token) { setMessage("가입 확인 메일을 확인한 뒤 로그인해 주세요."); return; } await fetch(`${publicUrl}/rest/v1/profiles`, { method: "POST", headers: { apikey: publicKey, Authorization: `Bearer ${data.access_token}`, "Content-Type": "application/json" }, body: JSON.stringify({ id: data.user.id, role: "student", display_name: email.split("@")[0] }) }); sessionStorage.setItem("literary-session", JSON.stringify(data)); setToken(data.access_token); await loadSession(data.access_token); setAuthOpen(false); setMessage("학생 계정이 생성되었습니다."); } else { const sign = await fetch(`${publicUrl}/auth/v1/token?grant_type=password`, { method: "POST", headers: { apikey: publicKey, "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await sign.json(); if (!sign.ok) throw new Error(data.msg || data.error_description); sessionStorage.setItem("literary-session", JSON.stringify(data)); setToken(data.access_token); await loadSession(data.access_token); setAuthOpen(false); setMessage("로그인했습니다."); } } catch (error) { setMessage(error instanceof Error ? error.message : "로그인에 실패했습니다."); } finally { setLoading(false); } }
  function logout() { sessionStorage.removeItem("literary-session"); setUser(null); setToken(""); setScreen("library"); }
  const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  async function publish(event: FormEvent) { event.preventDefault(); setLoading(true); try { const res = await fetch("/api/works", { method: "POST", headers: headers(), body: JSON.stringify({ ...form }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setMessage("해설이 학생용 자료로 출판되었습니다."); setForm(empty); setScreen("library"); searchWorks(""); } catch (error) { setMessage(error instanceof Error ? error.message : "출판하지 못했습니다."); } finally { setLoading(false); } }
  async function openWork(work: Work) { setSelected(work); setScreen("detail"); }
  async function startQuiz() { if (!selected || user?.role !== "student") { setMessage("형성평가는 학생 로그인 후 시작할 수 있습니다."); return; } setLoading(true); try { const res = await fetch(`/api/works/${selected.id}/quiz`, { method: "POST", headers: headers() }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setAttemptId(data.attemptId); setQuizQuestions(data.questions ?? []); setAnswers({}); setScreen("quiz"); } catch (error) { setMessage(error instanceof Error ? error.message : "형성평가를 시작하지 못했습니다."); } finally { setLoading(false); } }
  async function submitQuiz() { const score = quizQuestions.reduce((sum: number, item: any, index: number) => sum + (answers[item.id ?? String(index)] === item.answer ? 1 : 0), 0); const res = await fetch(`/api/attempts/${attemptId}`, { method: "PATCH", headers: headers(), body: JSON.stringify({ answers, score }) }); if (res.ok) setMessage(`형성평가가 저장되었습니다. ${quizQuestions.length}문항 중 ${score}문항 정답입니다.`); else setMessage("답안 저장에 실패했습니다."); }
  return <main><header><a className="brand" onClick={() => setScreen("library")}>문학<span>AI</span>실</a><nav><button onClick={() => setScreen("library")}>작품 찾기</button>{user?.role === "teacher" && <button onClick={() => setScreen("teacher")}>교사 작업실</button>}</nav><div className="identity">{user ? <><span>{user.role === "teacher" ? "교사" : "학생"} · {user.email}</span><button onClick={logout}>로그아웃</button></> : <button onClick={() => setAuthOpen(true)}>로그인</button>}</div></header><section className="top"><p>LITERATURE LEARNING PLATFORM</p><h1>교사는 출판하고,<br />학생은 탐구합니다.</h1><span>읽고 이해한 문학을 형성평가로 확인하는 학습 공간</span></section>{message && <div className="notice">{message}</div>}
  {screen === "library" && <section className="library"><div className="library-head"><div><p>STUDENT LIBRARY</p><h2>출판된 작품 자료</h2></div>{user?.role === "teacher" && <button className="primary" onClick={() => setScreen("teacher")}>새 해설 작성</button>}</div><div className="search"><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === "Enter" && searchWorks()} placeholder="작품명 또는 작자 검색"/><button onClick={() => searchWorks()}>검색</button></div><div className="cards">{works.map(work => <article key={work.id} onClick={() => openWork(work)}><p>{work.genre || "문학"}</p><h3>{work.title}</h3><span>{work.author || "작자 미입력"}</span><hr/><small>{work.theme || work.summary || "작품 해설 보기"}</small></article>)}{!works.length && <p className="empty">아직 출판된 작품이 없습니다. 교사가 해설을 작성해 출판하면 여기에 표시됩니다.</p>}</div></section>}
  {screen === "teacher" && <section className="teacher"><div className="teacher-head"><p>TEACHER STUDIO</p><h2>해설 작성과 출판</h2><span>교사는 작품 해설만 편안하게 작성해 출판합니다. 형성평가는 학생이 학습을 시작할 때 생성됩니다.</span></div><form onSubmit={publish}><div className="form-grid"><label>작품명<input required value={form.title} onChange={e => update("title", e.target.value)}/></label><label>작자<input value={form.author} onChange={e => update("author", e.target.value)}/></label><label>갈래<input value={form.genre} onChange={e => update("genre", e.target.value)} placeholder="현대시, 고전소설 등"/></label><label>주제<input value={form.theme} onChange={e => update("theme", e.target.value)}/></label></div><label>작품 원문 또는 발췌<textarea value={form.sourceText} onChange={e => update("sourceText", e.target.value)}/></label><label>내용 요약<textarea value={form.summary} onChange={e => update("summary", e.target.value)}/></label><label>표현상의 특징<input value={form.expressionFeatures} onChange={e => update("expressionFeatures", e.target.value)}/></label><label>교사 해설<textarea className="commentary" required value={form.commentary} onChange={e => update("commentary", e.target.value)} placeholder="줄거리, 인물·화자, 핵심 구절, 수업에서 강조할 내용을 자유롭게 작성하세요."/></label><button className="primary wide" disabled={loading}>{loading ? "해설을 출판하는 중입니다…" : "해설 출판하기"}</button></form></section>}
  {screen === "detail" && selected && <section className="work"><button className="back" onClick={() => setScreen("library")}>← 작품 목록</button><p>{selected.genre || "문학"}</p><h2>{selected.title}</h2><span>{selected.author}</span><div className="work-grid"><article className="reading"><h3>작품과 해설</h3><pre>{selected.source_text}</pre><h4>주제</h4><p>{selected.theme}</p><h4>내용 요약</h4><p>{selected.summary}</p><h4>교사 해설</h4><p>{selected.commentary}</p></article><aside><p>FORMATIVE QUIZ</p><h3>학습을 확인해 볼까요?</h3><span>학생이 시작하면 이 해설을 바탕으로 새로운 형성평가가 생성됩니다.</span><button className="primary" onClick={startQuiz} disabled={loading}>{loading ? "문제를 만드는 중입니다…" : "문제 생성하기"}</button><small>시작과 완료 기록은 내 학습 결과로 자동 저장됩니다.</small></aside></div></section>}
  {screen === "quiz" && selected && <section className="quiz"><button className="back" onClick={() => setScreen("detail")}>← 작품 해설로</button><p>FORMATIVE QUIZ · {selected.title}</p><h2>형성평가</h2>{quizQuestions.map((question: any, index: number) => { const id = question.id ?? String(index); return <article key={id}><b>{index + 1}. {question.stem}</b><div>{(question.choices ?? []).map((choice: any) => <label key={choice.number}><input type="radio" name={id} checked={answers[id] === choice.number} onChange={() => setAnswers(current => ({ ...current, [id]: choice.number }))}/>{choice.number}. {choice.text}</label>)}</div></article>; })}<button className="primary submit" onClick={submitQuiz}>답안 제출 및 결과 저장</button></section>}
  {authOpen && <div className="modal" onClick={() => setAuthOpen(false)}><form onSubmit={authenticate} onClick={e => e.stopPropagation()}><button type="button" className="x" onClick={() => setAuthOpen(false)}>×</button><p>{authMode === "login" ? "SIGN IN" : "STUDENT SIGN UP"}</p><h2>{authMode === "login" ? "로그인" : "학생 계정 만들기"}</h2><label>이메일<input type="email" value={email} onChange={e => setEmail(e.target.value)} required/></label><label>비밀번호<input type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={6}/></label><button className="primary wide" disabled={loading}>{authMode === "login" ? "로그인" : "학생 회원가입"}</button><button type="button" className="link" onClick={() => setAuthMode(authMode === "login" ? "signup" : "login")}>{authMode === "login" ? "학생 회원가입" : "로그인으로 돌아가기"}</button><small>교사 계정은 Supabase에서 교사 역할로 사전 등록해야 합니다.</small></form></div>}
  </main>;
}
