"use client";

import { FormEvent, Fragment, ReactNode, useEffect, useRef, useState } from "react";

type Role = "teacher" | "student" | null;
type User = { id: string; email?: string; role: Role; realName?: string; nickname?: string };
type Annotation = { id: string; phrase: string; note: string; tone: number; start?: number; end?: number; area?: "source" | "modern" };
type Group = "appreciation" | "summary" | "deep";
type ExtraSection = { id: string; group: Group; title: string; content: string };
type EditorBlocks = { modernTranslation: string; modernTranslationHidden?: boolean; authorIntro: string; deepInquiry: string };
type Work = {
  id: string; title: string; author?: string; genre?: string; theme?: string; summary?: string;
  source_text?: string; expression_features?: string; commentary: string; published_at?: string;
  generated_result?: { annotations?: Annotation[]; extraSections?: ExtraSection[]; authorImageUrl?: string; editorBlocks?: EditorBlocks };
};

const toneNames = ["파랑", "초록", "주황", "보라", "분홍", "무채색", "연보라", "빨강", "노랑", "청록"];
const emptyBlocks: EditorBlocks = { modernTranslation: "", modernTranslationHidden: false, authorIntro: "", deepInquiry: "" };
const blankForm = { title: "", author: "", genre: "현대시", sourceText: "", theme: "", expressionFeatures: "", summary: "", commentary: "", authorImageUrl: "" };

function poem(text: string | undefined, annotations: Annotation[], editable = false, onRemove?: (id: string) => void, area: "source" | "modern" = "source") {
  if (!text) return <p className="empty-copy">작품 원문을 입력하거나 불러와 주세요.</p>;
  const phraseOffsets = new Map<string, number>();
  const exact = annotations.filter((item) => (item.area || "source") === area).flatMap((item) => {
    if (Number.isInteger(item.start) && Number.isInteger(item.end) && (item.end || 0) > (item.start || 0)) return [item];
    // Older saved notes had no selection coordinates. Show only one best-match occurrence,
    // never every identical word, until the teacher saves the note again.
    const from = phraseOffsets.get(item.phrase) || 0; const start = text.indexOf(item.phrase, from);
    if (start < 0) return []; phraseOffsets.set(item.phrase, start + item.phrase.length);
    return [{ ...item, start, end: start + item.phrase.length }];
  });
  let cursor = 0;
  return text.split(/\r?\n/).map((line, lineIndex) => {
    const lineStart = cursor; const lineEnd = lineStart + line.length; cursor = lineEnd + 1;
    const matches = exact.filter((item) => (item.start || 0) < lineEnd && (item.end || 0) > lineStart).sort((a, b) => (a.start || 0) - (b.start || 0));
    let position = 0;
    const pieces: ReactNode[] = [];
    matches.forEach((item) => {
      const start = Math.max(0, (item.start || 0) - lineStart); const end = Math.min(line.length, (item.end || 0) - lineStart);
      if (start > position) pieces.push(<Fragment key={`text-${position}`}>{line.slice(position, start)}</Fragment>);
      if (end > start) pieces.push(<mark className={`poetic-term tone-${item.tone % toneNames.length}`} key={item.id} tabIndex={0} onMouseMove={(event) => window.dispatchEvent(new CustomEvent("literary-tooltip", { detail: { note: item.note, tone: item.tone % toneNames.length, x: event.clientX, y: event.clientY } }))} onMouseLeave={() => window.dispatchEvent(new Event("literary-tooltip-hide"))}>{line.slice(start, end)}<span className="term-tooltip">{item.note}</span></mark>);
      position = Math.max(position, end);
    });
    if (position < line.length) pieces.push(<Fragment key={`text-${position}`}>{line.slice(position)}</Fragment>);
    return (
    <p className={`poem-line${line ? "" : " stanza-break"}`} key={`${line}-${lineIndex}`}>
      {pieces.length ? pieces : "\u00a0"}
    </p>);
  });
}

function CursorTooltip() {
  const [tooltip, setTooltip] = useState<{ note: string; tone: number; x: number; y: number }>();
  useEffect(() => {
    const show = (event: Event) => setTooltip((event as CustomEvent<{ note: string; tone: number; x: number; y: number }>).detail);
    const hide = () => setTooltip(undefined);
    window.addEventListener("literary-tooltip", show); window.addEventListener("literary-tooltip-hide", hide);
    return () => { window.removeEventListener("literary-tooltip", show); window.removeEventListener("literary-tooltip-hide", hide); };
  }, []);
  return tooltip ? <div className={`cursor-tooltip tone-${tooltip.tone}`} style={{ left: Math.min(tooltip.x + 16, window.innerWidth - 320), top: Math.min(tooltip.y + 18, window.innerHeight - 100) }}>{tooltip.note}</div> : null;
}

function AttemptCards({ attempts, teacher = false }: { attempts: any[]; teacher?: boolean }) {
  if (!attempts.length) return <p className="empty">아직 제출한 형성평가가 없습니다.</p>;
  return <div className="history-list">{attempts.map((attempt) => <article key={attempt.id}><h3>{attempt.literary_works?.title || "작품"}</h3><small>{teacher && <>학생 {String(attempt.student_id || "").slice(0, 8)} · </>}{attempt.literary_works?.author || "작가 미입력"} · {attempt.completed_at ? new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "numeric", day: "numeric" }).format(new Date(attempt.completed_at)) : "저장됨"}</small><strong>{Number(attempt.score || 0)} / {(attempt.questions || []).length} 정답</strong>{(attempt.questions || []).map((question: any, index: number) => { const picked = attempt.answers?.[question.id || String(index)]; const correct = typeof question.answer === "number" ? question.answer : 0; const answerText = (value: number | undefined) => { const choice = question.choices?.[value ?? -1]; return typeof choice === "string" ? choice : choice?.text || "미응답"; }; return <div className={`history-question ${picked === correct ? "correct" : "wrong"}`} key={question.id || index}><b>{index + 1}. {question.question || question.stem}</b><span>{picked === correct ? "정답" : "오답"}</span><p>{teacher ? "학생 답" : "내 답"}: {answerText(picked)} · 정답: {answerText(correct)}</p></div>; })}</article>)}</div>;
}

function TeacherFeedback({ attempts, selectedStudent, onSelectStudent, onBack }: { attempts: any[]; selectedStudent: string; onSelectStudent: (id: string) => void; onBack: () => void }) {
  const students = Object.entries(attempts.reduce((groups: Record<string, any[]>, attempt) => { const id = attempt.student_id || "unknown"; (groups[id] ||= []).push(attempt); return groups; }, {}));
  if (selectedStudent) return <section className="history"><button className="back" onClick={onBack}>← 학생 목록으로</button><p>STUDENT FEEDBACK</p><h2>학생 학습 상세</h2><span>학생 {selectedStudent.slice(0, 8)}의 작품별 정오답 기록입니다.</span><AttemptCards attempts={attempts.filter((attempt) => attempt.student_id === selectedStudent)} teacher /></section>;
  return <section className="history"><button className="back" onClick={onBack}>← 작품 자료실로</button><p>STUDENT FEEDBACK</p><h2>학생 학습 상황</h2><span>학생을 선택하면 작품별 정오답과 점수를 확인할 수 있습니다.</span><div className="student-list">{students.map(([id, records]) => { const total = records.reduce((sum, record) => sum + Number(record.score || 0), 0); const count = records.reduce((sum, record) => sum + (record.questions || []).length, 0); return <button key={id} type="button" onClick={() => onSelectStudent(id)}><b>학생 {id.slice(0, 8)}</b><span>{records.length}회 제출 · {total} / {count} 정답</span></button>; })}</div>{!students.length && <p className="empty">아직 제출한 학생이 없습니다.</p>}</section>;
}

function TeacherFeedbackV2({ attempts, selectedStudent, onSelectStudent, onBack }: { attempts: any[]; selectedStudent: string; onSelectStudent: (id: string) => void; onBack: () => void }) {
  const students = Object.entries(attempts.reduce((groups: Record<string, any[]>, attempt) => { const id = attempt.student_id || "unknown"; (groups[id] ||= []).push(attempt); return groups; }, {}));
  const label = (records: any[], id: string) => { const savedProfile = records[0]?.answers?.__studentProfile; const name = records[0]?.student_name || savedProfile?.realName || "이름 미입력"; const nickname = records[0]?.student_nickname || savedProfile?.nickname; return `${name}${nickname ? ` · ${nickname}` : ""}`; };
  if (selectedStudent) { const records = attempts.filter((attempt) => attempt.student_id === selectedStudent); return <section className="history"><button className="back" onClick={() => onSelectStudent("")}>← 학생 목록으로</button><p>STUDENT FEEDBACK</p><h2>{label(records, selectedStudent)}의 학습 상세</h2><span>관리 번호: {selectedStudent.slice(0, 8)}</span><AttemptCards attempts={records} teacher /></section>; }
  return <section className="history"><button className="back" onClick={onBack}>← 작품 자료실로</button><p>STUDENT FEEDBACK</p><h2>학생 학습 상황</h2><span>학생을 선택하면 작품별 정오답과 점수를 확인할 수 있습니다.</span><div className="student-list">{students.map(([id, records]) => { const total = records.reduce((sum, record) => sum + Number(record.score || 0), 0); const count = records.reduce((sum, record) => sum + (record.questions || []).length, 0); return <button key={id} type="button" onClick={() => onSelectStudent(id)}><b>{label(records, id)}</b><span>{records.length}회 제출 · {total} / {count} 정답</span></button>; })}</div>{!students.length && <p className="empty">아직 제출한 학생이 없습니다.</p>}</section>;
}

function Publication({ form, annotations, blocks, extras, publishedAt, studentCheck, editor, update, updateBlock, addExtra, removeExtra, updateExtra, removeAnnotation, onChooseImage, onSelectSource, onSelectModern, onAddNote, onLoadSource, onSearchSources, onDeleteModern, onRestoreModern }: {
  form: typeof blankForm; annotations: Annotation[]; blocks: EditorBlocks; extras: ExtraSection[]; editor?: boolean;
  publishedAt?: string; studentCheck?: ReactNode;
  update?: (key: keyof typeof blankForm, value: string) => void; updateBlock?: (key: keyof EditorBlocks, value: string) => void;
  addExtra?: (group: Group) => void; removeExtra?: (id: string) => void; updateExtra?: (id: string, key: "title" | "content", value: string) => void; removeAnnotation?: (id: string) => void;
  onChooseImage?: (file?: File) => void; onSelectSource?: () => void; onSelectModern?: () => void; onAddNote?: (area: "source" | "modern") => void; onLoadSource?: () => void; onSearchSources?: () => void; onDeleteModern?: () => void; onRestoreModern?: () => void;
}) {
  const imageInput = useRef<HTMLInputElement>(null);
  const pageRef = useRef<HTMLElement>(null);
  useEffect(() => {
    const page = pageRef.current; const body = page?.querySelector<HTMLElement>(".literature-body");
    if (!body) return;
    const align = () => {
      const links = Array.from(body.querySelectorAll<HTMLAnchorElement>(".section-rail a"));
      ["appreciation", "summary", "deep", "check"].forEach((id, index) => {
        const section = body.querySelector<HTMLElement>(`#${id}`); const link = links[index];
        if (section && link) link.style.top = `${section.offsetTop}px`;
      });
    };
    const frame = requestAnimationFrame(align); const observer = new ResizeObserver(align); observer.observe(body); window.addEventListener("resize", align);
    return () => { cancelAnimationFrame(frame); observer.disconnect(); window.removeEventListener("resize", align); };
  }, [form.sourceText, form.theme, form.expressionFeatures, blocks.modernTranslation, blocks.modernTranslationHidden, blocks.authorIntro, blocks.deepInquiry, extras, annotations]);
  const editableText = (key: keyof typeof blankForm, value: string, placeholder: string, className = "") => editor
    ? <input className={`publication-input ${className}`} value={value} onChange={(e) => update?.(key, e.target.value)} placeholder={placeholder} aria-label={placeholder} />
    : <>{value || placeholder}</>;
  const editableBlock = (key: keyof EditorBlocks, value: string, placeholder: string) => editor
    ? <textarea className="section-editor" value={value} onChange={(e) => updateBlock?.(key, e.target.value)} placeholder={placeholder} />
    : <p className="section-copy">{value || "내용이 아직 등록되지 않았습니다."}</p>;
  const extra = (group: Group) => extras.filter((item) => item.group === group).map((item) => <div className="extra-block" key={item.id}>
    {editor ? <input value={item.title} aria-label="하위 항목 제목" onChange={(e) => updateExtra?.(item.id, "title", e.target.value)} /> : <h3>{item.title}</h3>}
    {editor ? <textarea value={item.content} aria-label="하위 항목 내용" onChange={(e) => updateExtra?.(item.id, "content", e.target.value)} /> : <p className="section-copy">{item.content}</p>}
    {editor && <button type="button" className="delete-inline" onClick={() => removeExtra?.(item.id)}>삭제</button>}
  </div>);
  const add = (group: Group) => editor && <button type="button" className="add-inline" onClick={() => addExtra?.(group)}>+ 하위 목록 추가</button>;
  const annotationManager = (area: "source" | "modern") => editor && <div className="annotation-manager inline-annotation-manager"><h4>{area === "source" ? "작품 원문 각주" : "현대어 풀이 각주"}</h4>{annotations.filter((item) => (item.area || "source") === area).length ? <ul>{annotations.filter((item) => (item.area || "source") === area).map((item) => <li key={item.id}><span className={`tone-${item.tone}`}>{item.phrase}</span><button type="button" onClick={() => removeAnnotation?.(item.id)}>이 각주 삭제</button></li>)}</ul> : <p>추가된 각주가 없습니다.</p>}</div>;
  const publishedDate = publishedAt ? new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "numeric", day: "numeric" }).format(new Date(publishedAt)) : "";
  return <><CursorTooltip /><article ref={pageRef} className={`published-page ${editor ? "publication-editor" : ""}`}>
    <div className="literature-header">
      <div className="genre-pill">{editor ? editableText("genre", form.genre, "갈래") : form.genre}</div>
      <div className={`author-portrait ${editor ? "is-drop-target" : ""}`} onClick={() => editor && imageInput.current?.click()} onDragOver={(e) => { if (editor) e.preventDefault(); }} onDrop={(e) => { if (editor) { e.preventDefault(); onChooseImage?.(e.dataTransfer.files[0]); } }}>
        {form.authorImageUrl ? <img src={form.authorImageUrl} alt="작가 이미지" /> : <span>{editor ? "이미지를 끌어 놓거나 클릭" : (form.author || "작가").slice(0, 1)}</span>}
        {editor && <input ref={imageInput} hidden type="file" accept="image/*" onChange={(e) => onChooseImage?.(e.target.files?.[0])} />}
      </div>
      <div className="title-block">
        <h1>{editableText("title", form.title, "작품명", "work-title")}</h1>
        <h3>{editableText("author", form.author, "작가명", "work-author")}</h3>
        <hr />
        <p>{editor ? "출판일은 해설을 출판할 때 자동으로 기록됩니다." : (publishedDate ? `출판일 · ${publishedDate}` : "출판일 정보 없음")}</p>
      </div>
    </div>
    <div className="literature-body">
      <aside className="section-rail"><a href="#appreciation">작품 감상</a><a href="#summary">작품 정리</a><a href="#deep">심화 감상</a>{studentCheck && <a href="#check">점검 학습</a>}</aside>
      <div className="literature-content">
        <section id="appreciation" className="literature-section"><div className="section-rule" /><article>
          <h3>작품 원문</h3>
          {editor ? <><label className="source-label">작품 원문 또는 발췌 <span><button type="button" onClick={onSearchSources}>인터넷 원문 검색</button><button type="button" onClick={onLoadSource}>AI 원문 불러오기</button></span></label><textarea className="source-editor" value={form.sourceText} onChange={(e) => update?.("sourceText", e.target.value)} onSelect={onSelectSource} placeholder="원문을 입력하고, 해설할 구절을 드래그해 선택하세요." />
            <div className="annotation-actions"><button type="button" onClick={() => onAddNote?.("source")}>선택한 구절에 각주 달기</button><span>각주가 적용된 모습</span></div><div className="poem editor-poem">{poem(form.sourceText, annotations, true, removeAnnotation, "source")}</div>{annotationManager("source")}</> : <div className="poem">{poem(form.sourceText, annotations, false, undefined, "source")}</div>}
          {!blocks.modernTranslationHidden && <><h3>현대어 풀이 {editor && <button type="button" className="remove-section" onClick={onDeleteModern}>현대어 풀이 삭제</button>}</h3>{editor ? <><textarea className="section-editor modern-editor" value={blocks.modernTranslation} onChange={(e) => updateBlock?.("modernTranslation", e.target.value)} onSelect={onSelectModern} placeholder="현대어 풀이를 작성하고 해설할 구절을 드래그해 선택하세요." /><div className="annotation-actions"><button type="button" onClick={() => onAddNote?.("modern")}>선택한 구절에 각주 달기</button><span>현대어 풀이 각주 미리보기</span></div><div className="poem editor-poem">{poem(blocks.modernTranslation, annotations, true, removeAnnotation, "modern")}</div>{annotationManager("modern")}</> : <div className="poem">{poem(blocks.modernTranslation, annotations, false, undefined, "modern")}</div>}</>}
          {editor && blocks.modernTranslationHidden && <button type="button" className="add-inline" onClick={onRestoreModern}>+ 현대어 풀이 추가</button>}
          {extra("appreciation")}{add("appreciation")}
        </article></section>
        <section id="summary" className="literature-section"><div className="section-rule" /><article>
          <h3>주제</h3>{editor ? <textarea className="section-editor" value={form.theme} onChange={(e) => update?.("theme", e.target.value)} placeholder="작품의 주제를 작성하세요." /> : <p className="section-copy">{form.theme || "내용이 아직 등록되지 않았습니다."}</p>}
          <h3>작가 소개</h3>{editableBlock("authorIntro", blocks.authorIntro, "작가 소개를 작성하세요.")}
          <h3>표현상의 특징</h3>{editor ? <textarea className="section-editor" value={form.expressionFeatures} onChange={(e) => update?.("expressionFeatures", e.target.value)} placeholder="표현상의 특징을 작성하세요." /> : <p className="section-copy">{form.expressionFeatures || "내용이 아직 등록되지 않았습니다."}</p>}
          {extra("summary")}{add("summary")}
        </article></section>
        <section id="deep" className="literature-section"><div className="section-rule" /><article>
          <h3>심화 탐구</h3>{editableBlock("deepInquiry", blocks.deepInquiry, "심화 탐구 내용을 작성하세요.")}
          {extra("deep")}{add("deep")}
        </article></section>
        {studentCheck && <section id="check" className="literature-section student-check-section"><div className="section-rule" /><article><h3>형성평가</h3>{studentCheck}</article></section>}
      </div>
    </div>
  </article></>;
}

export default function Home() {
  const [user, setUser] = useState<User | null>(); const [token, setToken] = useState("");
  const [screen, setScreen] = useState<"library" | "teacher" | "detail" | "quiz" | "history" | "profile" | "account">("library"); const [works, setWorks] = useState<Work[]>([]); const [selected, setSelected] = useState<Work>(); const [attempts, setAttempts] = useState<any[]>([]); const [selectedStudent, setSelectedStudent] = useState("");
  const [form, setForm] = useState(blankForm); const [blocks, setBlocks] = useState(emptyBlocks); const [editingId, setEditingId] = useState(""); const [annotations, setAnnotations] = useState<Annotation[]>([]); const [extras, setExtras] = useState<ExtraSection[]>([]);
  const [selectedPhrase, setSelectedPhrase] = useState(""); const [selection, setSelection] = useState<{ start: number; end: number }>(); const [selectedArea, setSelectedArea] = useState<"source" | "modern">("source"); const [note, setNote] = useState(""); const [tone, setTone] = useState(0); const [noteOpen, setNoteOpen] = useState(false);
  const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [categories, setCategories] = useState<string[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [activeMenu, setActiveMenu] = useState(""); const [authOpen, setAuthOpen] = useState(false); const [authMessage, setAuthMessage] = useState(""); const [authMode, setAuthMode] = useState<"login" | "signup">("login"); const [signupRole, setSignupRole] = useState<"teacher" | "student">("student"); const [teacherInviteCode, setTeacherInviteCode] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [realName, setRealName] = useState(""); const [nickname, setNickname] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  const [questions, setQuestions] = useState<any[]>([]); const [answers, setAnswers] = useState<Record<string, number>>({}); const [attemptId, setAttemptId] = useState(""); const [quizStatus, setQuizStatus] = useState("");
  const sourceRef = useRef<HTMLTextAreaElement>(null); const quizRequest = useRef<AbortController | null>(null); const publicUrl = process.env.NEXT_PUBLIC_SUPABASE_URL; const publicKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  const headers = () => ({ "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) });
  const update = (key: keyof typeof blankForm, value: string) => setForm((now) => ({ ...now, [key]: value }));
  const updateBlock = (key: keyof EditorBlocks, value: string) => setBlocks((now) => ({ ...now, [key]: value }));
  useEffect(() => { const saved = sessionStorage.getItem("literary-session"); if (saved) { const session = JSON.parse(saved); setToken(session.access_token); loadSession(session.access_token); } searchWorks(""); fetch("/api/works?categories=1").then((res) => res.ok ? res.json() : []).then(setCategories); }, []);
  useEffect(() => { if (screen !== "detail") quizRequest.current?.abort(); }, [screen]);
  async function loadSession(value = token) { const res = await fetch("/api/session", { headers: value ? { Authorization: `Bearer ${value}` } : {} }); setUser((await res.json()).user); }
  async function searchWorks(value = query, selectedCategory = category) { const params = new URLSearchParams(); if (value.trim()) params.set("q", value); if (selectedCategory) params.set("category", selectedCategory); const res = await fetch(`/api/works?${params.toString()}`); if (res.ok) setWorks(await res.json()); }
  async function openHistory() { if (user?.role !== "student") return; setLoading(true); try { const res = await fetch("/api/attempts", { headers: headers() }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setAttempts(data); setScreen("history"); } catch (error) { setMessage(error instanceof Error ? error.message : "학습 기록을 불러오지 못했습니다."); } finally { setLoading(false); } }
  function openProfile() { if (!user || user.role !== "student") return; setRealName(user.realName || ""); setNickname(user.nickname || ""); setScreen("profile"); }
  async function saveProfile() { setLoading(true); try { const res = await fetch("/api/profile", { method: "PATCH", headers: headers(), body: JSON.stringify({ realName, nickname }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); await loadSession(); setMessage("내 정보를 저장했습니다."); } catch (error) { setMessage(error instanceof Error ? error.message : "내 정보를 저장하지 못했습니다."); } finally { setLoading(false); } }
  async function openFeedback() { if (user?.role !== "teacher") return; setLoading(true); try { const res = await fetch("/api/teacher-feedback", { headers: headers() }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setAttempts(data); setSelectedStudent(""); setScreen("history"); } catch (error) { setMessage(error instanceof Error ? error.message : "학생 피드백을 불러오지 못했습니다."); } finally { setLoading(false); } }
  async function authenticate(event: FormEvent) { event.preventDefault(); setAuthMessage(""); if (!publicUrl || !publicKey) return setAuthMessage("Supabase 공개 환경 변수를 확인해 주세요."); if (authMode === "signup" && (!realName.trim() || !nickname.trim() || [...nickname.trim()].length > 7)) return setAuthMessage("이름과 7글자 이하 닉네임을 입력해 주세요."); setLoading(true); try { const res = authMode === "signup" ? await fetch("/api/signup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password, role: signupRole, realName: realName.trim(), nickname: nickname.trim(), teacherInviteCode }) }) : await fetch(`${publicUrl}/auth/v1/token?grant_type=password`, { method: "POST", headers: { apikey: publicKey, "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || data.msg || data.error_description); if (!data.access_token) { setAuthMessage("확인 메일을 열어 계정을 인증한 뒤 로그인해 주세요."); return; } sessionStorage.setItem("literary-session", JSON.stringify(data)); setToken(data.access_token); await loadSession(data.access_token); setAuthMessage(""); setPassword(""); setAuthOpen(false); } catch (error) { setAuthMessage(error instanceof Error ? error.message : "로그인에 실패했습니다."); } finally { setLoading(false); } }
  function openAccount() { if (!user) return; if (user.role === "student") return openProfile(); setNewPassword(""); setConfirmPassword(""); setMessage(""); setScreen("account"); }
  async function changePassword(event: FormEvent) { event.preventDefault(); if (!publicUrl || !publicKey) return setMessage("Supabase 공개 환경 변수를 확인해 주세요."); if (newPassword.length < 6) return setMessage("새 비밀번호는 6자 이상 입력해 주세요."); if (newPassword !== confirmPassword) return setMessage("새 비밀번호와 확인 입력이 일치하지 않습니다."); setLoading(true); setMessage(""); try { const res = await fetch(`${publicUrl}/auth/v1/user`, { method: "PUT", headers: { apikey: publicKey, Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ password: newPassword }) }); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.msg || data.error_description || data.error || "비밀번호를 변경하지 못했습니다."); setNewPassword(""); setConfirmPassword(""); setMessage("비밀번호를 변경했습니다."); } catch (error) { setMessage(error instanceof Error ? error.message : "비밀번호를 변경하지 못했습니다."); } finally { setLoading(false); } }
  function newTeacher() { setEditingId(""); setForm(blankForm); setBlocks(emptyBlocks); setAnnotations([]); setExtras([]); setScreen("teacher"); }
  function beginEdit(work: Work) { setEditingId(work.id); setForm({ title: work.title || "", author: work.author || "", genre: work.genre || "현대시", sourceText: work.source_text || "", theme: work.theme || "", expressionFeatures: work.expression_features || "", summary: work.summary || "", commentary: work.commentary || "", authorImageUrl: work.generated_result?.authorImageUrl || "" }); setBlocks(work.generated_result?.editorBlocks || emptyBlocks); setAnnotations(work.generated_result?.annotations || []); setExtras(work.generated_result?.extraSections || []); setScreen("teacher"); }
  function editSelected() { if (selected) beginEdit(selected); }
  async function editWork(work: Work) { const res = await fetch(`/api/works/${work.id}`); const data = await res.json(); if (!res.ok) return setMessage(data.error || "작품을 불러오지 못했습니다."); beginEdit(data); }
  function selectText(area: "source" | "modern") { const node = document.querySelector<HTMLTextAreaElement>(area === "source" ? ".source-editor" : ".modern-editor"); if (!node) return; const start = node.selectionStart; const end = node.selectionEnd; const phrase = node.value.slice(start, end); if (phrase.trim()) { setSelectedPhrase(phrase); setSelection({ start, end }); setSelectedArea(area); } }
  function addNote(area: "source" | "modern") { if (!selectedPhrase || selectedArea !== area) return setMessage(`${area === "source" ? "작품 원문" : "현대어 풀이"}에서 해설할 구절을 드래그해 선택해 주세요.`); setNote(""); setNoteOpen(true); }
  function saveNote() { if (!note.trim()) return setMessage("학생에게 보일 각주 설명을 입력해 주세요."); if (!selection) return setMessage("원문에서 다시 구절을 선택해 주세요."); setAnnotations((now) => [...now, { id: crypto.randomUUID(), phrase: selectedPhrase, note: note.trim(), tone, start: selection.start, end: selection.end, area: selectedArea }]); setSelectedPhrase(""); setSelection(undefined); setNoteOpen(false); }
  function addExtra(group: Group) { const title = window.prompt("새 하위 목록의 제목을 입력하세요."); if (!title?.trim()) return; setExtras((now) => [...now, { id: crypto.randomUUID(), group, title: title.trim(), content: "내용을 작성하세요." }]); }
  function imageFile(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => update("authorImageUrl", String(reader.result || "")); reader.readAsDataURL(file); }
  async function loadSource() { if (!form.title.trim() || !form.author.trim()) return setMessage("작품명과 작가명을 먼저 입력해 주세요."); setLoading(true); try { const res = await fetch("/api/works/source", { method: "POST", headers: headers(), body: JSON.stringify({ title: form.title, author: form.author }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); update("sourceText", data.sourceText); } catch (error) { setMessage(error instanceof Error ? error.message : "원문을 불러오지 못했습니다."); } finally { setLoading(false); } }
  function searchSources() { if (!form.title.trim() || !form.author.trim()) return setMessage("작품명과 작가명을 먼저 입력해 주세요."); const search = `${form.title} ${form.author} 원문`; window.open(`https://www.google.com/search?q=${encodeURIComponent(search)}`, "_blank", "noopener,noreferrer"); }
  async function publish(event: FormEvent) { event.preventDefault(); setLoading(true); try { const res = await fetch(editingId ? `/api/works/${editingId}` : "/api/works", { method: editingId ? "PATCH" : "POST", headers: headers(), body: JSON.stringify({ ...form, annotations, extraSections: extras, generatedResult: { editorBlocks: blocks } }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setMessage(editingId ? "수정한 해설을 다시 출판했습니다." : "해설을 출판했습니다. 학생 자료실에서 바로 검색할 수 있습니다."); setScreen("library"); searchWorks(""); } catch (error) { setMessage(error instanceof Error ? error.message : "출판하지 못했습니다."); } finally { setLoading(false); } }
  async function deleteWork(value?: unknown) { const workId = typeof value === "string" ? value : editingId; if (!workId || !window.confirm("이 출판물을 삭제할까요? 삭제하면 학생의 저장된 형성평가 기록도 함께 삭제되며 되돌릴 수 없습니다.")) return; setLoading(true); try { const res = await fetch(`/api/works/${workId}`, { method: "DELETE", headers: headers() }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setMessage("출판물을 삭제했습니다."); setActiveMenu(""); setEditingId(""); setScreen("library"); searchWorks(""); } catch (error) { setMessage(error instanceof Error ? error.message : "출판물을 삭제하지 못했습니다."); } finally { setLoading(false); } }
  async function openWork(work: Work) { const res = await fetch(`/api/works/${work.id}`); const data = await res.json(); if (!res.ok) return setMessage(data.error || "작품을 불러오지 못했습니다."); setSelected(data); setScreen("detail"); }
  async function startQuiz() { if (!selected || user?.role !== "student") return setMessage("형성평가는 학생 로그인 후에 시작할 수 있습니다."); quizRequest.current?.abort(); const controller = new AbortController(); quizRequest.current = controller; setQuizStatus(""); setLoading(true); try { const res = await fetch(`/api/works/${selected.id}/quiz`, { method: "POST", headers: headers(), signal: controller.signal }); const data = await res.json(); if (!res.ok) throw new Error(data.error); if (controller.signal.aborted) return; const normalized = (data.questions || []).map((item: any, index: number) => ({ ...item, id: item.id || `q${index + 1}`, question: item.question || item.stem || "문항", choices: (item.choices || []).map((choice: unknown) => typeof choice === "string" ? choice : String((choice as { text?: string }).text || "")), answer: typeof item.answer === "number" && item.answer > 0 && Array.isArray(item.choices) && typeof item.choices[0] !== "string" ? item.answer - 1 : Number(item.answer) || 0 })); if (!data.attemptId || !normalized.length) throw new Error("문제를 만들지 못했습니다. 다시 시도해 주세요."); setAttemptId(data.attemptId); setQuestions(normalized); setAnswers({}); } catch (error) { if ((error as Error).name !== "AbortError") setQuizStatus(error instanceof Error ? error.message : "형성평가를 만들지 못했습니다."); } finally { if (quizRequest.current === controller) { quizRequest.current = null; setLoading(false); } } }
  async function submitQuiz() { if (!attemptId) return setQuizStatus("저장할 형성평가 기록이 없습니다. 문제를 다시 생성해 주세요."); setLoading(true); const score = questions.reduce((sum, item, index) => sum + (answers[item.id || String(index)] === item.answer ? 1 : 0), 0); try { const res = await fetch(`/api/attempts/${attemptId}`, { method: "PATCH", headers: headers(), body: JSON.stringify({ answers, score }) }); const data = await res.json().catch(() => ({})); setQuizStatus(res.ok ? `답안을 저장했습니다. ${questions.length}문항 중 ${score}문항 정답입니다.` : (data.error || "답안 저장에 실패했습니다.")); } catch { setQuizStatus("네트워크 문제로 답안을 저장하지 못했습니다."); } finally { setLoading(false); } }
  return <main><header><button className="brand" onClick={() => setScreen("library")}>{"수\uE8A1니기는 국어시간"}</button><nav><button onClick={() => setScreen("library")}>작품 찾기</button>{user?.role === "teacher" && <><button onClick={newTeacher}>교사 작업실</button><button onClick={openFeedback}>학생 피드백</button></>}</nav><div className="identity">{user ? <><button className="account-link" onClick={openAccount}>{user.role === "teacher" ? "교사" : "학생"} · {user.email}</button><button onClick={() => { sessionStorage.removeItem("literary-session"); setUser(null); setToken(""); setMessage(""); setScreen("library"); }}>로그아웃</button></> : <button onClick={() => { setAuthMessage(""); setAuthOpen(true); }}>로그인</button>}</div></header>
    <section className="top"><p>LITERATURE LEARNING PLATFORM</p><h1 className="old-korean-title">{"수\uE8A1니기는 문학시간"}</h1><span>문학 작품의 해설과 형성평가를 한곳에서</span></section>{message && <div className="notice">{message}</div>}
    {screen === "library" && <section className="library"><div className="library-head"><div><p>STUDENT LIBRARY</p><h2>출판된 작품 자료</h2></div>{user?.role === "teacher" && <button className="primary" onClick={newTeacher}>새 해설 작성</button>}</div><div className="search"><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && searchWorks()} placeholder="작품명 또는 작가 검색" /><select value={category} aria-label="갈래별 작품 보기" onChange={(e) => { const next = e.target.value; setCategory(next); searchWorks(query, next); }}><option value="">모든 갈래</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select><button onClick={() => searchWorks()}>검색</button></div><div className="cards">{works.map((work) => <article key={work.id} onClick={() => openWork(work)}>{user?.role === "teacher" && <div className="card-menu"><button type="button" className="card-menu-trigger" aria-label={`${work.title} 관리 메뉴`} onClick={(event) => { event.stopPropagation(); setActiveMenu((now) => now === work.id ? "" : work.id); }}>⋯</button>{activeMenu === work.id && <div className="card-menu-popover"><button type="button" onClick={(event) => { event.stopPropagation(); editWork(work); }}>수정하기</button><button type="button" className="danger" onClick={(event) => { event.stopPropagation(); deleteWork(work.id); }}>삭제하기</button></div>}</div>}<p>{work.genre || "문학"}</p><h3>{work.title}</h3><span>{work.author || "작가 미입력"}</span><hr /><small className="work-opening">{work.source_text?.split(/\r?\n/).find((line) => line.trim()) || "작품 원문이 등록되지 않았습니다."}</small></article>)}{!works.length && <p className="empty">아직 출판된 작품이 없습니다.</p>}</div></section>}
    {screen === "teacher" && <section className="teacher-inline"><div className="teacher-head"><p>TEACHER STUDIO</p><h2>출판 지면에서 바로 작성하기</h2><span>제목·작가·이미지·각주와 하위 목록을 이 페이지에서 바로 편집합니다.</span></div><form onSubmit={publish}><Publication form={form} annotations={annotations} blocks={blocks} extras={extras} editor update={update} updateBlock={updateBlock} addExtra={addExtra} removeExtra={(id) => setExtras((now) => now.filter((item) => item.id !== id))} updateExtra={(id, key, value) => setExtras((now) => now.map((item) => item.id === id ? { ...item, [key]: value } : item))} removeAnnotation={(id) => setAnnotations((now) => now.filter((item) => item.id !== id))} onChooseImage={imageFile} onSelectSource={() => selectText("source")} onSelectModern={() => selectText("modern")} onAddNote={addNote} onLoadSource={loadSource} onSearchSources={searchSources} onDeleteModern={() => { setBlocks((now) => ({ ...now, modernTranslationHidden: true })); setAnnotations((now) => now.filter((item) => item.area !== "modern")); }} onRestoreModern={() => setBlocks((now) => ({ ...now, modernTranslationHidden: false }))} /><section className="annotation-manager"><h3>추가된 각주</h3>{annotations.length ? <ul>{annotations.map((item) => <li key={item.id}><span className={`tone-${item.tone}`}>{item.area === "modern" ? "현대어 풀이" : "작품 원문"} · {item.phrase}</span><button type="button" onClick={() => setAnnotations((now) => now.filter((value) => value.id !== item.id))}>이 각주 삭제</button></li>)}</ul> : <p>아직 추가된 각주가 없습니다.</p>}</section><div className="publish-bar">{editingId && <button type="button" className="delete-publication" disabled={loading} onClick={deleteWork}>출판물 삭제</button>}<button type="button" onClick={() => setScreen("library")}>취소</button><button className="primary" disabled={loading}>{loading ? "처리 중…" : editingId ? "수정 내용 다시 출판" : "해설 출판하기"}</button></div></form></section>}
    {screen === "detail" && selected && <><section className="detail-actions"><button className="back" onClick={() => setScreen("library")}>← 자료실로</button>{user?.role === "teacher" && <><button className="edit-published" onClick={editSelected}>수정하기</button><button type="button" className="delete-published" disabled={loading} onClick={() => deleteWork(selected.id)}>삭제하기</button></>}</section><Publication form={{ title: selected.title || "", author: selected.author || "", genre: selected.genre || "문학", sourceText: selected.source_text || "", theme: selected.theme || "", expressionFeatures: selected.expression_features || "", summary: selected.summary || "", commentary: selected.commentary || "", authorImageUrl: selected.generated_result?.authorImageUrl || "" }} annotations={selected.generated_result?.annotations || []} blocks={selected.generated_result?.editorBlocks || emptyBlocks} extras={selected.generated_result?.extraSections || []} publishedAt={selected.published_at} studentCheck={user?.role === "student" ? <div className="student-check"><p>이 작품의 해설과 원문만 바탕으로 AI 형성평가 문제를 만듭니다.</p><button onClick={startQuiz} disabled={loading}>{loading ? "문제를 만드는 중…" : "문제 생성하기"}</button>{questions.length > 0 && <div className="inline-quiz"><h4>생성된 형성평가</h4>{questions.map((item, index) => <fieldset key={item.id || index}><legend>{index + 1}. {item.question}</legend>{(item.choices || []).map((choice: string, choiceIndex: number) => <label key={`${item.id}-${choiceIndex}`}><input type="radio" name={item.id || String(index)} checked={answers[item.id || String(index)] === choiceIndex} onChange={() => setAnswers((now) => ({ ...now, [item.id || String(index)]: choiceIndex }))} />{choice}</label>)}</fieldset>)}<button type="button" className="save-answers" disabled={loading} onClick={submitQuiz}>{loading ? "저장 중…" : "답안 저장"}</button>{quizStatus && <p className="quiz-status">{quizStatus}</p>}</div>}</div> : undefined} /></>}
    {screen === "profile" && <section className="profile-page"><button className="back" onClick={() => setScreen("library")}>← 작품 자료실로</button><p>MY PROFILE</p><h2>내 정보 관리</h2><span>이름과 닉네임은 교사가 학생 학습 상황을 확인할 때 표시됩니다.</span><label>이름<input value={realName} onChange={(event) => setRealName(event.target.value)} placeholder="예: 홍길동" /></label><label>닉네임 <small>최대 7글자</small><input value={nickname} maxLength={7} onChange={(event) => setNickname(event.target.value)} placeholder="예: 문학소년" /></label><button className="primary" disabled={loading} onClick={saveProfile}>{loading ? "저장 중…" : "내 정보 저장"}</button><button className="profile-history" onClick={openHistory}>내 형성평가 기록 보기</button></section>}
    {screen === "account" && user?.role === "teacher" && <section className="profile-page"><button className="back" onClick={() => setScreen("library")}>← 작품 자료실로</button><p>TEACHER ACCOUNT</p><h2>교사 정보 관리</h2><span>로그인 계정을 확인하고 새 비밀번호로 변경할 수 있습니다.</span><label>이메일<input type="email" value={user.email || ""} readOnly /></label><form onSubmit={changePassword}><label>새 비밀번호 <small>6자 이상</small><input required minLength={6} type="password" autoComplete="new-password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><label>새 비밀번호 확인<input required minLength={6} type="password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} /></label><button className="primary" disabled={loading}>{loading ? "변경 중…" : "비밀번호 변경"}</button></form></section>}
    {screen === "history" && (user?.role === "teacher" ? <TeacherFeedbackV2 attempts={attempts} selectedStudent={selectedStudent} onSelectStudent={setSelectedStudent} onBack={() => setScreen("library")} /> : <section className="history"><button className="back" onClick={() => setScreen("library")}>← 작품 자료실로</button><p>MY LEARNING</p><h2>내 형성평가 기록</h2><span>제출한 문항의 정답과 오답을 한곳에서 확인합니다.</span><AttemptCards attempts={attempts} /></section>)}
    {screen === "quiz" && <section className="quiz"><button className="back" onClick={() => setScreen("detail")}>← 작품 해설로</button><h2>형성평가</h2><p>문항을 풀고 제출하면 답안이 저장됩니다.</p>{questions.map((item, index) => <article key={item.id || index}><b>{index + 1}. {item.question}</b>{(item.choices || []).map((choice: string, choiceIndex: number) => <label key={choice}><input type="radio" name={item.id || String(index)} checked={answers[item.id || String(index)] === choiceIndex} onChange={() => setAnswers((now) => ({ ...now, [item.id || String(index)]: choiceIndex }))} />{choice}</label>)}</article>)}<button className="primary submit" onClick={submitQuiz}>답안 저장</button></section>}
    {authOpen && <div className="modal"><form onSubmit={authenticate}><button type="button" className="x" onClick={() => { setAuthMessage(""); setAuthOpen(false); }}>×</button><p>{authMode === "signup" ? "ACCOUNT SIGN UP" : "SIGN IN"}</p><h2>{authMode === "signup" ? "계정 만들기" : "로그인"}</h2>{authMessage && <div className="auth-message" role="alert">{authMessage}</div>}{authMode === "signup" && <><label>가입 유형<select value={signupRole} onChange={(e) => setSignupRole(e.target.value as "teacher" | "student")}><option value="student">학생</option><option value="teacher">교사</option></select></label>{signupRole === "teacher" && <label>교사 초대 코드<input required type="password" value={teacherInviteCode} onChange={(e) => setTeacherInviteCode(e.target.value)} placeholder="관리자에게 받은 초대 코드" /></label>}<label>이름<input required value={realName} onChange={(e) => setRealName(e.target.value)} placeholder="예: 홍길동" /></label><label>닉네임 <small>최대 7글자</small><input required maxLength={7} value={nickname} onChange={(e) => setNickname(e.target.value)} placeholder="예: 문학소년" /></label></>}<label>이메일<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>비밀번호<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="primary" disabled={loading}>{authMode === "signup" ? `${signupRole === "teacher" ? "교사" : "학생"} 회원가입` : "로그인"}</button><button type="button" className="link" onClick={() => { setAuthMessage(""); setAuthMode(authMode === "login" ? "signup" : "login"); }}>{authMode === "login" ? "회원가입으로 이동" : "로그인으로 돌아가기"}</button><small>교사 가입은 관리자에게 받은 초대 코드가 있어야 완료됩니다.</small></form></div>}
    {noteOpen && <div className="note-dialog-backdrop"><section className="note-dialog"><button type="button" className="note-dialog-close" onClick={() => setNoteOpen(false)}>×</button><h2>각주 내용</h2><p className={`note-dialog-phrase tone-${tone}`}>{selectedPhrase}</p><label>표시 색</label><div className="note-dialog-tones">{toneNames.map((name, index) => <button key={name} className={`tone-${index}${tone === index ? " active" : ""}`} type="button" onClick={() => setTone(index)}>{name}</button>)}</div><label>학생에게 보여 줄 설명</label><textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="이 시어·구절에 대한 해설을 작성하세요." /><div className="note-dialog-actions"><button type="button" onClick={() => setNoteOpen(false)}>취소</button><button type="button" className="save" onClick={saveNote}>각주 넣기</button></div></section></div>}
  </main>;
}
